#!/bin/bash

Adding_Users () {
        read -p 'Username: ' usr
        read -p 'Comment:  ' cmnt
        read -p 'User ID:  ' uid
        read -p 'Group:    ' grp
        if [[ $(sudo cat /etc/passwd | grep $usr) ]];then
                echo "user $usr already exist!"
        else
                sudo useradd $usr -c $cmnt -u $uid -g $grp
                sudo mkdir /home/$usr/.ssh
                sudo chown $usr:$grp /home/$usr/.ssh ; sudo chmod 700 /home/$1/.ssh
                sudo ssh-keygen -t rsa -N "" -f /home/$usr/.ssh/id_rsa 2>/dev/null
                sudo chown $usr:$grp /home/$usr/.ssh/id_rsa ; sudo chown $usr:$grp /home/$usr/.ssh/id_rsa.pub
                sudo touch /home/$usr/.ssh/authorized_keys ; sudo cp /home/$usr/.ssh/id_rsa.pub /home/$usr/.ssh/authorized_keys ; sudo chmod 600 /home/$usr/.ssh/authorized_keys
                sudo chown $usr:$grp /home/$usr/.ssh/authorized_keys
                sudo cp /home/$usr/.ssh/id_rsa.pub /tmp ; sudo chmod 777 /tmp/id_rsa.pub
        fi
}
Adding_Users $usr $cmnt $uid $grp

